### ISSUE TITLE
function 'as_cholmod_sparse' not provided by package 'Matrix'

### ISSUE THREAD

**Issue by tjogzt** [OSCA-source/OSCA.intro#3]
Hi, I had some troubles when I ran some codes in your OSCA
ebook. I ran the Quick start (simple) part. It gave the following error messages:

> # PCA.
> library(scater)
> set.seed(1234)
> sce <- runPCA(sce, ncomponents=25, subset_row=hvg)
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'

So I can't continue. Even I updated all packages and re-installed Matrix package.
I expect your response. Thanks!

**Comment by alanocallaghan** [comment]
See: https://github.com/alanocallaghan/scater/issues/201

You might want to try running

```r
install.packages("Matrix")
install.packages("irlba")
```

Sorry about this, but unfortunately it's out of our hands as we don't control the Matrix or irlba packages and there's not really anything we can do to fix other people's packages.

**Comment by Varix** [comment]
There is actually an interesting upstream bug right now. Its hurting a lot of PCA and UMAP R packages, even the non-Bioconductor ones...

Most people are fixing it by uninstalling and re-installing arlba (which is calling the Matrix here)

```
remove.packages('irlba')
install.packages('irlba')
```

**Comment by adho13396** [comment]
Error in (function (A, nv = 5, nu = nv, maxit = 1000, work = nv + 7, reorth = TRUE,  : 
  function 'as_cholmod_sparse' not provided by package 'Matrix'
  
 I have the same problem this week weheres I had no problem last week on 22.3.24. working with Monocle 3 for preprocessing, Clustering, etc. I have removed and reinstalled "Matrix", "irlba", Monocle 3, the whole R and R-Studio and installed "gfortran" etc. All to no Avail and the problem persistent since then (Updating some packages that I could not even remember.

**Comment by alanocallaghan** [comment]
The problem is upstream, not in OSCA nor even in Bioc

**Comment by apal6** [comment]
Hi, 

I am still have the issues, even after updating the pacakges. 

`install.packages("Matrix",type="source", dependencies=T) 
install.packages("irlba",type="source", dependencies=T)
cds<-preprocess_cds(cds,num_dim=30)`

Any advice?

Thank you

**Comment by adho13396** [comment]
I have been struggling with the same issues for the past 10 days, ever since I updated my R program to 4.3.3.
No solution has been identified yet. I asked various experts and nobody has yet a workable answer.

Von: Aastha Pal ***@***.***>
Antworten an: "OSCA-source/OSCA.intro" ***@***.***>
Datum: Dienstag, 2. April 2024 um 21:20
An: "OSCA-source/OSCA.intro" ***@***.***>
Cc: ***@***.***" ***@***.***>, Comment ***@***.***>
Betreff: Re: [OSCA-source/OSCA.intro] function 'as_cholmod_sparse' not provided by package 'Matrix' (Issue #3)


Hi,

I am still have the issues, even after updating the pacakges.

install.packages("Matrix",type="source", dependencies=T) install.packages("irlba",type="source", dependencies=T) cds<-preprocess_cds(cds,num_dim=30)

Any advice?

Thank you

**Comment by alanocallaghan** [comment]
> install.packages("Matrix",type="source", dependencies=T)  install.packages("irlba",type="source", dependencies=T) cds<-preprocess_cds(cds,num_dim=30)
Any advice?

You would have to restart your R session for this to work
